pythondjango/aperitivos/urls.py
from django.urls import path

from pythondjango.aperitivos.views import indice, video

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pythondjango/base/urls.py
from django.urls import path

from pythondjango.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
    
]

pythondjango/modulos/urls.py
from django.urls import path
from pythondjango.modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe',),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice'),
]   

pythondjango/turmas/urls.py
from django import views
from django.urls import path
from pythondjango.turmas import views

app_name = 'turmas'

urlpatterns = [
    path('', views.indice, name='indice'),
]

pythondjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pythondjango.base.urls')),
    path('aperitivos/', include('pythondjango.aperitivos.urls')),
    path('modulos/', include('pythondjango.modulos.urls')),
    path('turmas/', include('pythondjango.turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
         path('__debug__/', include('debug_toolbar.urls'))
    )

pythondjango/aperitivos/models.py
from django.db import models
from django.urls import reverse

class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))    

    def __str__(self):
        return f'Video: {self.titulo}'   

pythondjango/base/models.py
from argparse import _CountAction
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail

class UserManager(BaseUserManager):
    use_in_migrations = True


    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    

class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User Class
    
    Username and password are required. Other fields are optional.
    """
    
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pythondjango/modulos/models.py
from email.policy import default
from enum import unique

from django.db import models
from django.forms import SlugField
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)
    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})
    


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)
    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})
        

pythondjango/turmas/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Turmas(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turmas, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pythondjango/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pythondjango.aperitivos.models import Video


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})
    

pythondjango/base/views.py
from django.http import HttpResponse
from django.shortcuts import render
from pythondjango.modulos import facade

# Create your views here.

def home(request):
   return render(request, 'base/home.html', {'MÓDULOS': facade.listar_modulos_ordenados()})

pythondjango/modulos/views.py
from django.shortcuts import render
from pythondjango.modulos import facade
from django.contrib.auth.decorators import login_required

def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)

def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})

@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})

pythondjango/turmas/views.py
from django.shortcuts import render

def indice(request):
    return render(request, 'turmas/indice.html')
    

pythondjango/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}

<title> {% block title %} Python Pro - Aperitivos {% endblock title %} </title>
<meta name="description" content="{% block description%} Páginas com todos os vídeos gratuitos {% endblock description %}">

{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">Lista de videos de Aperitivos</h1>
            <ol>
                {% for video in videos %}
                <li><a href="{{ video.get_absolute_url }}">{{ video.titulo }}</a></li>
                {% empty %}
                    <spam>Não foi encontrado nenhum vídeo de aperitivo</spam>
                {% endfor %}
            </ol>
        </div>    
</div>
{% endblock body%}

pythondjango/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}

<title> {% block title %}Python Pro - Aperitivo{% endblock title %} </title>
<meta name="description" content="{% block description%}Página de video gratuido do Python Pro{% endblock description %}">

{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="margin-bottom:5%;margin-top:5%">{{ video.titulo | default:"Faltando título" }}</h1>
                <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="1000" height="562"
                        frameborder="5" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>

<script src="https://player.vimeo.com/api/player.js"></script>
{% endblock body%}

pythondjango/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro - Home{% endblock title %}</title>

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
    <meta name="author" content="Vinicius Braga">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown"
                aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Módulos
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        {% for modulo in MODULOS %}
                            <li><a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{ modulo.titulo }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.first_name }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                        <div class="dropdown-item">
                            <a class="btn btn-danger" href=" {% url 'logout' %}"> Sair </a>
                        </div>    
                    </ul>
                </li>
            </ul>
        {% else %}

        <a href="{% url 'login'  %}" class="btn btn-light me-md 2">Entrar</a>

        {% endif %}    
        </div>




    </div>
</nav>

{% block body %}{% endblock body %}
<!--Rodapé-->

{% include 'base/footer.html' with contato_email='ramalho@python.pro.br' only %}
</body>
</html>

pythondjango/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="ow">
            <div class="col">
                <h3>Entre em contato</h3>
                <address>
                    +55 12 997-411-855
                    <br/>
                    <a href="mailto:{{ contato_email }}" class="text-light">{{ contato_email }}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Todos os direitos reservados
                </div>
            </div>
        </div>
    </div>    
</footer>

pythondjango/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

<title> {% block title %}Python Pro - Home{% endblock title %} </title>

{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="text">
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">
                            Search
                        </button>
                    </form>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            <!--descrição do curso-->
            <div class="jumbotron">
                <h2>
                    Curso de Python com Luciano Ramalho
                </h2>

                <h4 class="mt-4">Matriculas abertas! Custo R$1000,00</h4> 
                <!-- INICIO DO BOTAO PAGSEGURO -->
                <a href="https://pag.ae/7XZKSWCr2/button" target="_blank" title="Pagar com PagSeguro"><img src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif" alt="Pague com PagSeguro - é rápido, grátis e seguro!" /></a>
                <!-- FIM DO BOTAO PAGSEGURO -->



                   <h4 class="mt-4">Entre na fila de espera</h4> 
                <form action="https://herokuapp.us14.list-manage.com/subscribe/post?u=e94e85e3872b442df8520d305&amp;id=0a6cd34778" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class=" form-row align-items-center" target="_blank" novalidate>
                    <div class="col-auto">
                      <label class="visually-hidden" for="mce-EMAIL">Email</label>
                      <input type="email" value="" name="EMAIL" class="form-control required " id="mce-EMAIL" placeholder="exemplo@gmail.com">
                    </div>
                    <div class="col-auto">
                      <label class="visually-hidden" for="mce-FNAME"></label>
                      <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Seu nome aqui "> 
                    </div>
                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e94e85e3872b442df8520d305_0a6cd34778" tabindex="-1" value=""></div>
                    <div class="col-auto">
                        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class=" btn btn-primary">
                    </div>    
                </form>
            </div>

            <!--Detalhes sobre o Luciano Ramalho-->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <h6 class="card-header mt-n2">
                            Mais detalhes sobre o instrutor
                        </h6>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/luciano-ramalho.png' %}" alt="Foto de luciano Ramalho" class="img-thumbnail float-start me-3"/>
                                Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e autor do Livro <a href="https://www.amazon.com.br/Python-Fluente-Programa%C3%A7%C3%A3o-Concisa-Eficaz/dp/857522462X" target="_blank">Python Fluente</a>
                                Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web. Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e outros, usando Python desde 1998. Como instrutor, atendeu clientes como Citibank, CPqD, Serpro, Presidência da República, Globo.com e Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou a criar a Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e fundador do Garoa Hacker Clube, o primeiro hackerspace do Brasil.


                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body%}

pythondjango/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
<title> {% block title %}Python Pro - Aperitivo{% endblock title %} </title>
<meta name="description" content="{% block description%}Página de video gratuido do Python Pro{% endblock description %}">

{% block body%}    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{aula.modulo.titulo}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{aula.titulo}}</li>
        </ol>
    </nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="margin-bottom:5%;margin-top:5%">{{ aula.titulo | default:"Faltando título" }}</h1>
                <iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}" width="1000" height="562"
                        frameborder="5" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
        </div>
</div>

{% endblock body%}

pythondjango/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}Página com detalhes do módulo {{modulo.titulo}}{% endblock description %}
{% block body %}
<div class="container">
{% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endfor %}
</div>
{% endblock body %}

pythondjango/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}

<title> {% block title %}{{modulo.titulo}}{% endblock title %} </title>
<meta name="description" content="{% block description%}Página com detalhes do módulo {{modulo.titulo}} {% endblock description %}">

{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="margin-bottom:5%;margin-top:5%">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <!--Para descrição-->
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
        </div>
    </div>
</div>

<script src="https://player.vimeo.com/api/player.js"></script>
{% endblock body%}

pythondjango/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Indice de Turmas{% endblock title %}
{% block description %}Página com todas as turmas do curson Python Pro{% endblock description %}

{% block body %}
<div class="container">
{% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público</dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição</dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endfor %}
</div>
{% endblock body %}